# Generated by Django 3.0.4 on 2020-04-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200413_0831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Scores',
        ),
    ]
