# Generated by Django 3.0.4 on 2020-04-19 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200419_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_challenges',
            name='date_defi_releve',
            field=models.DateTimeField(default=datetime.date(2020, 4, 19)),
        ),
    ]
