# Generated by Django 3.0.4 on 2020-04-19 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20200419_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_challenges',
            name='date_defi_releve',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 18, 30, 28, 471074, tzinfo=utc)),
        ),
    ]
