# Generated by Django 3.0.4 on 2020-04-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20200419_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_challenges',
            name='date_defi_releve',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
