# Generated by Django 3.0.4 on 2020-04-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20200419_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
    ]
