# Generated by Django 3.0.4 on 2020-04-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20200420_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted_challenges',
            name='nb_essai',
        ),
    ]
