# Generated by Django 3.0.5 on 2020-04-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20200425_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='ville',
        ),
    ]
